[package]
org = "wso2"
name = "EpicFhirR4AdministrationApiService"
version = "0.9.0"
distribution = "2201.12.3"

# [[dependency]]
# org = "ballerinax"
# name = "health.fhir.r4"
# version = "5.1.0"

# [[dependency]]
# org = "ballerinax"
# name = "health.fhirr4"
# version = "1.3.1"

# [[dependency]]
# org = "ballerinax"
# name = "health.clients.fhir"
# version = "2.0.0"

[build-options]
observabilityIncluded = true
